apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-stage

resources:
  - ../../base

images:
  - name: placeholder/gitops-demo-app
    newName: kimtaejung/gitops-demo-app
    newTag: latest

patches:
  - path: patch-replicas.yaml
  - path: patch-configmap.yaml
  - path: patch-ingress.yaml
